### ISSUE TITLE
Error: uploading FLS

### ISSUE THREAD

**Issue by metanav** [vshymanskyy/w600tool#1]
I was able to upload *.img successfully. But micropython shell was not started. I think I have to burn *.fls first to make it work. But I am getting the following error:
```
$ python3 w600tool-master/w600tool.py -p /dev/tty.wchusbserial1410 --upload W60X_MicroPython_1.10_B1.5_img/1M_Flash/wm_w600.fls

Opening device: /dev/tty.wchusbserial1410
Erasing secboot
Error: Erasing secboot failed => Try entering ROM boot manually
```

PS: I am using Air602 WiFi Development Board from Seeed and I do not think there is a way to initiate ROM boot manually.

**Comment by vshymanskyy** [comment]
It's tricky, but not impossible (I did it a few times):

> Entering ROM bootloader is a lot more difficult: it requires grounding pin 13 when powering on the W600 chip. However, pin 13 is located on the tiny 5mm x 5mm QFN32 package only; it does not have a header pin on the development board or a "stamp hole" on the inner Air602 board. To ground pin 13, I had to align a jumper wire to the correct trace, and at the same time plug the board into a USB port. I only had to do it once to recover after uploading a wrong AT firmware.

from: https://yoursunny.com/t/2018/Air602-blink/
